version: '3'
services:
  mysql_server:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - mysql_data_container:/var/lib/sql
    restart: always
    environment:
      MYSQL_HOST: mysql_server
      MYSQL_DATABASE: typeorm
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    networks:
      - web
  adminer:
    image: adminer
    restart: always
    networks:
      - web
    ports:
      - 8080:8080

volumes:
  mysql_data_container:

networks:
  web:
    driver: bridge
